### ISSUE TITLE
Auto ad skipping (30s) not working

### ISSUE THREAD

**Issue by Brissinger** [x0a/uBO-YouTube#21] opened 2020-10-08 16:34 UTC
Hi again.
Auto skipping 30s is not working but 5s option is working. Latest firefox.
#bug

**Comment by x0a** [comment] 2020-10-14 06:15
Hey Brissinger,

Sorry I missed this one and for the super late response. I've been able to reproduce the bug on consecutive ads where the first ad is 15s and the second one is 30s+. Does this match what you've been seeing?

It is likely due to the fact that we check video.src to see if it matches the video we originally detected. If it doesn't it doesn't do any skipping. This one will likely a lot of refactoring since the .src check is important so we don't accidentally skip the actual video.

I'll work on this over the next 2-3 days.

**Comment by Brissinger** [comment] 2020-10-15 19:17
Hi
I tested it again and i had e.g 2 ads -1of2 ad had 36s and it was displayed for full 36s, not skipped. Then started 2nd ad and it was 30s. 5s option do skip ad in right moment.

**Comment by Brissinger** [comment] 2020-10-15 19:18
> 
> 
> Hey Brissinger,
> 
> Sorry I missed this one and for the super late response. I've been able to reproduce the bug on consecutive ads where the first ad is 15s and the second one is 30s+. Does this match what you've been seeing?
> 
> It is likely due to the fact that we check video.src to see if it matches the video we originally detected. If it doesn't it doesn't do any skipping. This one will likely a lot of refactoring since the .src check is important so we don't accidentally skip the actual video.
> 
> I'll work on this over the next 2-3 days.

Hi
I tested it again and i had e.g 2 ads -1of2 ad had 36s and it was displayed for full 36s, not skipped. Then started 2nd ad and it was 30s. 5s option skipped ad when i turned it off and on again with slider. Maybe something is wrong with remembering/loading auto ad skipping option still?

**Comment by x0a** [comment] 2020-10-17 00:00
Thanks for the clarification.

There's a way to find out for sure. If you open up the [settings](https://youtube.com/ubo-yt#ads) (without changing anything), press F12 and expand the object next to `Received settings:`, what does it say next to autoSkipSeconds? There may be a bug on the content side but we can at least confirm that the settings page is receiving the settings properly.
![Screenshot 2020-10-16 185725](https://user-images.githubusercontent.com/13019784/96323354-65361200-0fe2-11eb-8e00-fa92b61da86e.png)

But before you do that, can you update to v0.11.9, refresh YT, and see if there's been an improvement? I pushed a fix to resolve the bug that I was able to witness (related to yours), and it maybe might fix this bug as well.

**Comment by Brissinger** [comment] 2020-10-17 10:35
> 
> 
> Thanks for the clarification.
> 
> There's a way to find out for sure. If you open up the [settings](https://youtube.com/ubo-yt#ads) (without changing anything), press F12 and expand the object next to `Received settings:`, what does it say next to autoSkipSeconds? There may be a bug on the content side but we can at least confirm that the settings page is receiving the settings properly.
> ![Screenshot 2020-10-16 185725](https://user-images.githubusercontent.com/13019784/96323354-65361200-0fe2-11eb-8e00-fa92b61da86e.png)
> 
> But before you do that, can you update to v0.11.9, refresh YT, and see if there's been an improvement? I pushed a fix to resolve the bug that I was able to witness (related to yours), and it maybe might fix this bug as well.

(i didn't changed any settings/sliders for this and next session)
1 I checked console first
![11111](https://user-images.githubusercontent.com/72404411/96334755-93f3cd00-1062-11eb-8d0d-cae0c75412e7.JPG)
2 I updated addon and restarted Firefox
3 I checked console again it looks the same as before
4 I looked for an ad over 30s long and it got skipped after 30s (1of 2 ad 1min long)
It seems it works now, thanks man :)
Btw in Polish translation file there is no "Right arrow key to force skip ads" string to translate :)

**Comment by x0a** [comment] 2020-10-17 15:19
> Btw in Polish translation file there is no "Right arrow key to force skip ads" string to translate :)

Yes of course! I will upload the source file today.

Happy to hear its working now, feel free to re-open if it acts up again.
Thanks

**Closed as completed by x0a** 2020-10-17 15:19 UTC
Labels: bug
